### ISSUE TITLE
doc: Error in redirect link to LinkedIn

### ISSUE THREAD

**Issue by KesleyDavid** [juntossomosmais/venice#7]
**Describe the bug**
When I click on the link to LinkedIn I am redirected to a non-existent profile

**Reproduce**
1. Go to README.md
2. Under Author, click on LinkedIn
3. We are redirected to non-existent profile

**Expected behavior**
Redirection to Juntos Somos Mais LinkedIn Profile

**Screenshots**
![image](https://user-images.githubusercontent.com/39314443/82331396-725ebe80-99ba-11ea-94ec-fa63efc98020.png)

![image](https://user-images.githubusercontent.com/39314443/82331057-ffedde80-99b9-11ea-8bb9-0d5cde30daff.png)

**Desktop:**
- OS: Ubuntu
- Chrome browser
- Version 83 Beta

**Additional context**
Documentation update required

**Comment by KesleyDavid** [comment]
Good morning everyone, this is my first open source contribution, I hope it will be the first of many. For the first time, I took courage and went ahead.

I wish I could change and make a Pull Request with the correction.

I hope I can contribute to the project

**Comment by felipefialho** [comment]
Thanks for report @KesleyDavid, we are waiting your PR 😄

**Comment by KesleyDavid** [comment]
Good morning, the change was made and a Pull Request was created #8

**Comment by felipefialho** [comment]
WoW, amazing @KesleyDavid and congratz for your first contribution ❤️ 

I hope it is the first of many 🥇

**Comment by KesleyDavid** [comment]
I thank you!
Without a doubt it will be the first of many!
It's great to see a repo with a little piece that you put something in there :1st_place_medal: :smile:
